### ISSUE TITLE
I made a Mistake

### ISSUE THREAD

**Issue by ZiggyMaster** [UnCrevard/LiveStreamingDownloader#1]
I accidentally deleted the recording part of the Videos in Settings.
How do I write a text? For each video to have a separate name?
... in the field?

**Comment by UnCrevard** [comment]
service_country_username_date_title_type_bid_uid

this ?

**Comment by ZiggyMaster** [comment]
I m talking about this two area. I deleted there and i don't find anything what i write to fix this problem. When i record someone i can't see any file name. It's record with only (.) filename. What should i write in there?


Outlook<http://aka.ms/weboutlook>'tan gönderildi

________________________________
Gönderen: UnCrevard <notifications@github.com>
Gönderildi: 9 Kasım 2018 Cuma 13:54:42
Kime: UnCrevard/LiveStreamingDownloader
Bilgi: ZiggyMaster; Author
Konu: Re: [UnCrevard/LiveStreamingDownloader] I made a Mistake (#1)


service_country_username_date_title_type_bid_uid

this ?

**Comment by ZiggyMaster** [comment]
I m talking about this two area. I deleted there and i don't find anything what i write to fix this problem. When i record someone i can't see any file name. It's record with only (.) filename. What should i write in there?




Outlook<http://aka.ms/weboutlook>'tan gönderildi

________________________________
Gönderen: Metal Love <trista-pena@hotmail.com>
Gönderildi: 9 Kasım 2018 Cuma 17:12:55
Kime: UnCrevard/LiveStreamingDownloader
Konu: Ynt: [UnCrevard/LiveStreamingDownloader] I made a Mistake (#1)


I m talking about this two area. I deleted there and i don't find anything what i write to fix this problem. When i record someone i can't see any file name. It's record with only (.) filename. What should i write in there?


Outlook<http://aka.ms/weboutlook>'tan gönderildi

________________________________
Gönderen: UnCrevard <notifications@github.com>
Gönderildi: 9 Kasım 2018 Cuma 13:54:42
Kime: UnCrevard/LiveStreamingDownloader
Bilgi: ZiggyMaster; Author
Konu: Re: [UnCrevard/LiveStreamingDownloader] I made a Mistake (#1)


service_country_username_date_title_type_bid_uid

this ?
