### ISSUE TITLE
What should I do to make a website like http://liveomg.com/ ?

### ISSUE THREAD

**Issue by Periscoper** [UnCrevard/LiveStreamingDownloader#4]
What should I do to make a website like http://liveomg.com/ ? How could you upload content from this Site? Can you help me a little? I want to make a site exactly like Liveomg. And I want to automatically get content from Liveomg.

**Comment by UnCrevard** [comment]
just learn how to scrap live from multiple sources (npm is full of cli tools). but keep in mind they are changing regularly their API so you site can die at any moment😊

**Comment by Periscoper** [comment]
I read it over and over again for 1 day to understand what you said, but I didn't understand anything you said. I have no experience on this subject. What I want from you is that you can help me with this. I just want to make a website like Liveomg or Betterscope.net I don't know programs like CLI or NPM. Can you explain it as simple as I am stupid?

**Comment by UnCrevard** [comment]
if you know nothing about programming or web dev you will fail.
